# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudemu" do
  version "2.11.0"

  on_macos do
    on_arm do
      sha256 "51986df76fd14e359fcdb152b0b4ae2262e233389c857dc94ec52a95bcfd7c7b"
      url "https://github.com/stackshy/cloudemu/releases/download/v#{version}/cloudemu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1c150e701ff7dbc1fbb1469385fed9b5864eeb4a447d22b5d124ad65029836a1"
      url "https://github.com/stackshy/cloudemu/releases/download/v#{version}/cloudemu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0eb4379b97fa27c6daa89a24333dbcfe39b8ec4cec6fa5b30c9b6923a179c35d"
      url "https://github.com/stackshy/cloudemu/releases/download/v#{version}/cloudemu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "480e3b74679daf24b2c8f606137c9d9703b8c32659dfa690ac3d42ad9017c058"
      url "https://github.com/stackshy/cloudemu/releases/download/v#{version}/cloudemu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cloudemu"
  desc "In-memory emulator for AWS, Azure & GCP cloud APIs — run a local cloud, $0."
  homepage "https://cloudemu.info/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloudemu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cloudemu"]
    end
  end

  # No zap stanza required
end
