# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudemu" do
  version "2.10.0"

  on_macos do
    on_arm do
      sha256 "1f224329e4b0bb8b2414f2837ab87dc0ece038269459bb70c9ee21b606fded8c"
      url "https://github.com/stackshy/cloudemu/releases/download/v#{version}/cloudemu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b70cf990dbf62b14b4151b88a670cc64cb369e4090c09badc41b3531a4276769"
      url "https://github.com/stackshy/cloudemu/releases/download/v#{version}/cloudemu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "13904c10efb9aecec7e2fefdefd0f6ac561399fcde45c1d517fe4c421864d5b2"
      url "https://github.com/stackshy/cloudemu/releases/download/v#{version}/cloudemu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a3ebf83365506d78c4850c94be5884dc9c5d52eaa305730ffccc30a6cdb68586"
      url "https://github.com/stackshy/cloudemu/releases/download/v#{version}/cloudemu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cloudemu"
  desc "In-memory emulator for AWS, Azure & GCP cloud APIs — run a local cloud, $0."
  homepage "https://cloudemu.info/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloudemu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cloudemu"]
    end
  end

  # No zap stanza required
end
