# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudemu" do
  version "2.12.0"

  on_macos do
    on_arm do
      sha256 "5e6df0c0a244f23e9e4bb94ba8dd1c137a2b094fd521112d984786d93ae954e0"
      url "https://github.com/stackshy/cloudemu/releases/download/v#{version}/cloudemu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9ff4120806295fcd966a08c4163192d43742f25f461d541398bd2c0ff01a94d0"
      url "https://github.com/stackshy/cloudemu/releases/download/v#{version}/cloudemu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fcb66714728073b388fa2c2039541dc2d918b3f2147e9f426db4391aed0d03aa"
      url "https://github.com/stackshy/cloudemu/releases/download/v#{version}/cloudemu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a3e20b7bd5a1532484d8e46df1fc8f272fc016dd2671ba5bcedf2c1113340397"
      url "https://github.com/stackshy/cloudemu/releases/download/v#{version}/cloudemu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cloudemu"
  desc "In-memory emulator for AWS, Azure & GCP cloud APIs — run a local cloud, $0."
  homepage "https://cloudemu.info/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloudemu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cloudemu"]
    end
  end

  # No zap stanza required
end
